# https://mpv.io/manual/stable/

screenshot-directory="~/Pictures/mpv"
screenshot-format=avif
volume=50
volume-max=200

# Не выключать плеер после окончания видео
keep-open=yes
# Показывать окно, даже если это аудиофайл
force-window=yes
# Сохранить позицию, на которой остановился в прошлый раз
save-position-on-quit=yes

# Will disable the default UI
osc = no
# Optional, but recommended. Will remove the window titlebar and frame. You can still drag a window by dragging the video.
border = no

# YouTube
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=cookies-from-browser=chromium
demuxer-max-bytes=1GiB
demuxer-max-back-bytes=1GiB
